apiVersion: v2
appVersion: 1.22-alpha.4ee56447daf484a90d92376703519b3b3fc6bf7e
description: Helm chart for deploying Istio gateways
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio
- gateways
name: gateway
sources:
- https://github.com/istio/istio
type: application
version: 1.22-alpha.4ee56447daf484a90d92376703519b3b3fc6bf7e
