apiVersion: v1
appVersion: 1.22-alpha.4ee56447daf484a90d92376703519b3b3fc6bf7e
description: Helm chart for istio-cni components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-cni
- istio
name: cni
sources:
- https://github.com/istio/istio/tree/master/cni
version: 1.22-alpha.4ee56447daf484a90d92376703519b3b3fc6bf7e
